# Cheatsheet Lecture 1a

This first part of this lecture deals with:

* Getting Google Colab up and running,
* Getting to know variables and simple data types, and
* Learning how to do some simple operations on that data.

# Python introduction

## Variables

A _variable_ is a container for storing data values.
- _Naming of a variable_: A variable name can contain only letters, numbers, and underscores. They can start with a letter or an underscore, but not with a number. Spaces cannot be used in variables. The best variable names are informative, such as using ```average_score``` as a variable name for a list of average scores. An example of a bad variable name is ```Average Score```.
- _Assigning values to a variables_: You can assign values (information) to a variable by using the ```=``` sign, for example, you can create the variable ```number_two``` and assign the number ```2``` to this like so: ```number_two = 2```. See below about how you can use the ```print()``` function to access the value assigned to a variable.
-_case-sensitive_: Python is a case-sensitive programming language. This means that it treats uppercase and lowercase letters differently. For example, x and X are not seen as the same variable, student and Student also not the same, etc.
-_overwriting_: Note that if you declare a variable and assign it some value, if you assign the variable again with another value, Python will only use the lastly declared value. In other words, it will overwrite the variable and assign it the new value.

## Data Types 

During this class, we'll work with three data types:
- _String_: A string is a sequence of characters. Strings in Python are surrounded by either single quotation marks, or double quotation marks. Strings can have capital and lowercase letters and spaces in between. An example of a string is ```"Hello World"```.
- _Integer_: An integer is a whole number, positive or negative, without decimals, of unlimited length. An example of an integer is ```0``` or ```1```.
- _Float_: A float, or "floating point number" is a number, positive or negative, containing one or more decimals. An example of a float is ```0.5``` or ```1.0```.

If you want to figure out what data type an object is, you can use the built-in function ```type()```:
- _Type_: The ```type()``` function returns the type of the specified object.

- _Comment_: Comments can be used to explain Python code. They have various purposes, they can be used to make the code more readable and they can be used to prevent execution when testing code. A comment is created by starting a line with a ```#```. An example of a comment is ```# This is a comment.```

## Operators

It is often convenient to be able to apply operators to your variables. There are many many _operators_ in Python, but you will only need to learn a subset:

- _Addition_: ```x + y```
- _Subtraction_: ```x - y```
- _Multiplication_: ```x * y```
- _Division_: ```x / y```
- _Modulus_: ```x % y```
    - _EXPLANATION_: The modulo operation returns the remainder of a division, after one number is divided by another (called the modulus of the operation). Given two positive numbers x and y, x modulo y (often abbreviated as x mod y) is the remainder of the division of x by y, where x is the dividend and y is the divisor. For example, the expression "5 mod 2" evaluates to 1, because 5 divided by 2 has a quotient of 2 and a remainder of 1, while "9 mod 3" would evaluate to 0, because 9 divided by 3 has a quotient of 3 and a remainder of 0.
- _Exponentiation_: ```x ** y```
    - _EXPLANATION_: Exponentiation is done via the so-called power operator ( ** ) which raises the left value to the power of the second value. For example: 2 ** 3 is 2 times 2 times 2 equals 8.
- _Floor division_: ```x // y```
    - _EXPLANATION_: Floor division is a mathematical operation that is used to divide two numbers and get the result in which the quotient is rounded down to the nearest integer value. For example, 8/3 has a non-integer value of 2.6667 ; so, applying the floor division operator would return a value of 2 .
- _Assignment_: ```x = y```
- _Equal_: ```x == y```
- _Not equal_: ```x != y```
- _Greater than_: ```x > y```
- _Less than_: ```x < y```
- _Greater than or equal to_: ```x >= y```
- _Less than or equal to_: ```x <= y```

## Printing results

Finally, it is useful to be able to print out the result of an operation or the value of a variable on screen so you can inspect if something went wrong. You can do that with the built-in function print.
- _Print_: The ```print()``` function prints the specified message to the screen. An example of using the ```print()``` function is if we want to access the value we assigned to the ```number_two``` variable above. With ```print(number_two)``` we will access ```2```.

## Importing a library

Python has a lot of standard functionality built in, but often you'll need to create extra functionality. You can do that by importing so-called libraries.

- A _library_ is a collection of reusable Python code that can be applied to other program development projects.
For example, there is a library specifically for working with data sets. It has functions for analyzing, cleaning, exploring, and manipulating data. This library is called _Pandas_ and we will be using it in this lecture.
- _import_: In order to use the functions that are contained in a library, you need to _import_ that library. You do that at the beginning of your script, and from that moment on you can use the functions that are contained within that library. For example, if you type ```import pandas as pd``` you import the library Pandas with the name _pd_. You can can access the functions through the `pd` alias as well. This means that, would you want to use the pandas function that reads in a csv file called ```read_csv```, which is included in the Pandas library you can now use that function by typing `pd.read_csv`. You can find more information here: https://docs.python.org/3/reference/import.html

## Exploring a dataset using Pandas

As introduced above, we will be using the Pandas library to explore a dataset. The Pandas library is a powerful tool for data analysis. It offers convenient functions that make working with data (more) easy and intuitive.

You can import pandas as mentioned above. Make sure you read the section above on how to import a library, and how to use it (for example, you know why we use `pd.___`)

### Importing data to a DataFrame
After import pandas, you can use the following functions and objects to explore a dataset:

- `read_csv` and `read_excel`: Using these functions you open a csv or Excel (xlsx or xls) file. You can find more information here: [read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) and [read_excel](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html).
- `DataFrame`: If you use `read_csv` or `read_excel`, you get a Pandas DataFrame in return. A Pandas DataFrame is basically an Excel sheet: a 2 dimensional data structure, with rows and columns. You can find more information here: [DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html).

In [6]:
import pandas as pd

# When you use 'read_csv' you get a "DataFrame". We're storing it as 'example_df'
example_df = pd.read_csv('https://gist.githubusercontent.com/Louren/ee3f3fed3f7b620a329e4676f1394123/raw/08f5a3e17d6852c782a9602a3bf181a352ee2213/Example_data.csv')

# We then use the 'head' function to show our data
example_df.head()

4


### Analyzing a DataFrame
Once you have a DataFrame, you can use the following functions and objects to explore the data:
- `describe`: The ```describe()``` method returns description of the data in the DataFrame. For example, if you have a DataFrame that is called df, you can obtain the description of the data by typing ```df.describe()```. You can find more information here: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html.
- _head_ and _tail_: The ```head()``` and ```tail()``` methods respectively return the first and last six rows of a dataframe. The number of rows shown can be adjusted by changing this from the default six rows. You can find more information here: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html.

### Slicing and dicing a DataFrame
If we have a DataFrame defined, it is important to be able to slice, dice, and generally get and set subsets of Pandas objects. You can do that in various ways:

- ```loc[]```: This method is label based, but may also be used with a boolean array. It takes two inputs, the first is for rows and the second for the column. So, if for a DataFrame called _df_ you want the column with label "student" and then the row with label 4, you need to use ```df.loc['4','student']```. If you want all rows for the column "student" you type ```df.loc[:,'student']```. If you want to select for example rows with index 4 through 11, you can ```df.loc[4:11,'student']```, and if you want to see more columns, for example both students and energy, you can type it as follows: ```df.loc[4:11,['students','energy']]```. Note here, that both single, ```''``` and double ```""``` quote marks work.
- ```iloc[]```: This method is based on integer positions (from 0 to ```length-1``` of the axis), but may also be used with a boolean array. So, if for a DataFrame called df you want the column with index 5 and then the row with index 4, you need to use ```df.iloc[4,5]```. If you want all rows for the column "student" you type ```df.iloc[:,5]```. **IMPORTANT: Python starts indexing from 0!**

You can find more information here: https://pandas.pydata.org/docs/user_guide/indexing.html

In [ ]:
# Using the data we imported above, we can now use the newly learned functions to analyze it.
example_df.describe()

In [ ]:
example_df.loc[3,'Column1']

### Filtering a DataFrame using conditions

In this section we will filter a DataFrame - just like you would do in Excel. In Excel you have to perform several manual clicks/actions to filter data, but in Python you can do this with a single line of code. 

To filter in Pandas, you have to tell Pandas the "conditions" that need to be met. This is how you could do that:

**Single condition**:
To get _all_ rows of DataFrame ```df``` where, in in column ```price``` the value is greater than 20, you can use ```df[df["price"] > 20]```.

**Multiple conditions**:
You can use this way of conditional indexing to create subsets based on multiple conditions. For example, ```df[(df["price"] > 20) | (df["quantity"] > 20)]```, will provide a subset of the ```df``` DataFrame with only the rows where in columns ```price``` **or** ```quantity``` the values are greater than 20. If you want to access data with multiple _and_ conditions, you can use the ```&``` operator.


df[<span style="color:blue">(df["x"] > 0.5)</span> <span style="color:orange">|</span> <span style="color:blue">(df["y"] > 0.5)</span>]
* In <span style="color:blue">Blue, you can see the conditions</span> that are used to subset the data. Notice they are in brackets? This is important to separate the conditions.
* The <span style="color:orange;">|</span> is the _or_ operator. This means that if either of the conditions is met, the row will be included in the subset.


Short recap:
- ```|``` is the _or_ operator
- ```&``` is the _and_ operator
- Brackets `(` and `)` are important to separate the conditions. They work the same way as in mathematics.

In [9]:
# Lets use the `example_df` again, and now filter the data using the new method
example_df[example_df['Column3'] > 50]

   Column1  Column2  Column3
7        8       16       64
8        9       18       81
9       10       20      100

In [10]:
# And now with two conditions - notice the use of the brackets?
example_df[(example_df['Column3'] > 50) & (example_df['Column2'] < 19)]

   Column1  Column2  Column3
7        8       16       64
8        9       18       81

Refer to the examples in Practicum 1a for more information on how to use these functions and objects.

# Compound data structures

The second part of this lecture deals with compound data structures. These are data structures that can hold multiple data types. We will be working with lists, tuples, sets, and dictionaries.

**Lists**

A Python _list_ is a collection of items, enclosed in ```[ ]``` and separated by commas. Lists can contain different types of data (e.g. strings, integers, float). An example of a list is ```["horse", "cat", "dog"]```.
- _Assigning a list to a variable_: You can assign a list to a variable using a ```=``` (as discussed in Lecture 1), for example, ```animals = ["horse", "cat", "dog"]```.
- _Indexing a list_: Every item in a list is defined by an index, starting from 0. For example, in our ```animals``` list, the item ```"horse"``` has the ```0``` index position and the item ```"cat"``` has the ```1``` index position.
- _Slicing a list_: You can access individual or subset of items from a list through slicing using ```[]``` with the index number(s). For example, you can access the item ```"horse"``` through ```animals[0]```. The sliced subset will always return n-1 of the indexes called. For example, you will return the items ```"horse"``` and ```"cat"``` through ```animals[0:2]```, but if you want all three items you have to call ```animals[0:3]```. You do not have to access items in a sequence, since you can   also use the sytax ```[start:stop:step]```.For example, ```animals[0:3:2]``` will return the items ```"horse"``` and ```"dog"```.
- _Adding items to a list_: You can add items to a list using either ```append()``` or ```insert()```. When using ```append()``` will add the item to the end of the list, for example ```animals.append("tiger")``` results in ```animals = ["horse", "cat", "dog", "tiger"]```. When using ```insert()``` you can specify the location of where you want to add the item with the index, for example, ```animals.insert(1, "tiger")``` results in ```animals = ["horse", "tiger", "cat", "dog"]```. You can also use the ```+``` to add two or more lists together.
- _Deleting items from a list_: You can remove items from a list using ```remove()``` and specifying the list item, for example, after runing ```animals.remove("horse")``` results in just ```["cat", "dog"]```. You can also remove items using the item index and the ```del()``` function, for example, ```del animals[0]``` also results in just ```["cat", "dog"]```.
- _Getting the length of a list_: You figure out how many items are in a list using the ```len()``` function, for example, ```len(animals)``` returns ```3``` indicating that there are three items in the list.

**Tuples**

_Tuples_ are used to store multiple items in a single variable, written with round brackets, ```()```, for example, ```fruits = ("apple", "banana", "cherry", "apple", "cherry")```. Tuples can also be created from lists using ```tuple(list)```. Like lists, tuples can contain multiple data types. Unlike lists, they are collections of elements that are ordered and unchangeable. When we say that tuples are ordered, it means that the items have a defined order, and that order will not change. Tuples are unchangeable, meaning that we cannot change, add or remove items after the tuple has been created. The advantage of using a tuples over lists is that they are faster than lists. Tuples make the code safe from any accidental modification. If a data is needed in a program which is not supposed to be changed, then it is better to put it in tuples than in lists.
- _Indexing a tuple_: Tuples are indexed in the same way as lists.
- _Slicing a tuple_: Tuples are sliced in the same way as lists.
- _Adding items to a tuple_: You can add items to a tuple using ```+```, for example, ```more_fruits = fruits + ("mango")``` results in ```("apple", "banana", "cherry", "apple", "cherry", "mango")```.
- _Deleting items in a tuple_: You cannot remove items from a tuple.
- _Getting the length of a tuple_: You can get the length of a tuple in the same way as for lists.

**Sets**

_Sets_ are used to store multiple elements in a single variable, using ```{}```, for example, ```cars = {"BMW", "Mercedes", "Fiat"}```. A set is a collection which is unordered, unchangeable, and unindexed. A set cannot contain duplicates. In this way, they are useful in identifying differences in two tuples. We will not work with sets in this course.

**Dictionaries**

_Dictionaries_ are used to store data values in ```key:value``` pairs using ```{}```, for example, ```car_info = {"brand": "Ford", "model": "Mustang", "year": 1964}```. A dictionary can also be created by zipping two lists together, using ```dict(zip(list_1, list_2))```. A dictionary is a collection which is ordered, changeable and do not allow duplicates.
- _Indexing a dictionary_: Dictionaries are made up of keys and values, which are indexed either according to their names (e.g. ```"brand"```) or index number (e.g. ```0```). See _Slicing a dictionary_ for more information.
- _Slicing a dictionary_: Dictionaries can be indexed as individual lists by using ```keys()``` and ```values()```. Items can be called individually by first calling either the keys or values as a list using ```list()```. Keys can be called using ```keys()``` and indexed like a list, for example, ```list(car_info.keys())[0]``` will return ```"brand"```. Similarly, values can be called using ```values()``` and indexed like a list, for example, ```list(car_info.values())[0]``` will return ```"Ford"```. Additionally, you can call the value associated with a specific key using ```get()```, for example, ```car_info.get("model")``` returns ```"Mustang"```.
- _Adding items to a dictionary_: You can add a new key:value pair to a dictionary through ```dict[key] = value```, for example, ```car_info["colour"] = "red"``` results in the following dictionary ```car_info = {"brand": "Ford", "model": "Mustang", "year": 1964, "colour": "red"}```.
- _Deleting items from a dictionary_: You can remove an item from a dictionary in the same way as you would delete an item from a list.
- _Changing items in a dictionary_: You can update a dictionary in the same way that you would add items to the dictionary, for example ```car_info["model"] = "Focus"``` results in the following dictionary ```car_info = {"brand": "Ford", "model": "Focus", "year": 1964}```.  
- _Getting the length of a dictionary_: You can get the length of a tuple in the same way as for lists.